/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.71"

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    mavenLocal()
    jcenter()
}


//________________________________________________________________________________
// DEPENDENCY VERSIONS
//________________________________________________________________________________
val guavaVersion =  "28.0-jre"
val jacksonVersion = "2.10.3"
val juniperVersion  =  "5.4.0"
val koinVersion  =  "2.1.5"
val kotlinVersion =  "1.3.71"
val kotlinCoroutinesVersion =  "1.3.6"
val vertxVersion = "3.9.0"
val assertjVersion = "3.16.1"

//________________________________________________________________________________
// DEPENDENCIES
//________________________________________________________________________________

dependencies {

    implementation("com.c0ckp1t:c0ckp1t-common:1.0.0-SNAPSHOT")
    implementation("com.c0ckp1t:c0ckp1t-engine:1.0.0-SNAPSHOT")



    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    implementation( "com.fasterxml.jackson.module:jackson-module-kotlin:$jacksonVersion")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:$kotlinCoroutinesVersion")
    implementation("io.vertx:vertx-core:$vertxVersion")
    implementation("io.vertx:vertx-web-client:$vertxVersion")
    implementation ("io.vertx:vertx-lang-kotlin:$vertxVersion") {
        exclude("org.jetbrains.kotlin:kotlin-stdlib-jre8:1.2.20")
    }

    // TEST
    testImplementation("org.junit.jupiter:junit-jupiter-api:$juniperVersion")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:$juniperVersion")
    testImplementation ("io.mockk:mockk:1.9.1")
    testImplementation("org.assertj:assertj-core:$assertjVersion")

}

application {
    // Define the main class for the application.
    mainClassName = "c0ckp1t.content.public.AppKt"
}
